### ISSUE TITLE
Incompatibility with current Maven repository of Amodeus

### ISSUE THREAD

**Issue by grauwelf** [amodeus-science/amod#184]
I have encountered an unresolvable import of ch.ethz.refactoring.AmodeusConfigurator and ch.ethz.idsc.amodeus.analysis.plot.AmodeusChartUtils. 

It looks like amod went ahead of current Maven repository of amodeus. 
The package ch.ethz.refactoring appeared in amodeus 6 days ago while the last deployment to the mvn-repo was 8 days ago.

**Comment by sebhoerl** [comment]
From the beginning of this week, we're currently in a major refactoring and restructuring as many contributors will leave/change institutes in the next months. For now, I would recommend using the Maven packages, or going back to the commit for the 1.9.3 release in all repositories.

**Comment by grauwelf** [comment]
Got it, thanks!
Would be good to have this information in READMEs of both repositories.

**Comment by claudioglasses** [comment]
Hi grauwelf, tensor has been deployed and should work again, otherwise, just let me know. Btw: we are happy to provide access in case you are willing to contribute. Best regards
